"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In produzione: imposta SECRET_KEY nell'ambiente (es. export SECRET_KEY="...")
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-(jg5rx3#6a!lw*wpbvmq*%o*2v_o25wuzt^3w5-_l(m+%7l&x8')

# SECURITY WARNING: don't run with debug turned on in production!
# In produzione: imposta DJANGO_DEBUG=0 (o DEBUG=0)
_render_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '').strip()
_is_render = bool(_render_hostname or os.environ.get('RENDER'))
_debug_raw = os.environ.get('DJANGO_DEBUG', os.environ.get('DEBUG'))
if _debug_raw is None:
    # Safe default: local dev stays in debug, Render defaults to production mode.
    DEBUG = not _is_render
else:
    DEBUG = _debug_raw.strip().lower() in ('1', 'true', 'yes', 'on')

# In produzione: imposta ALLOWED_HOSTS (es. ALLOWED_HOSTS=gadly.it,www.gadly.it)
_PRODUCTION_HOSTS = ("gadly.it", "www.gadly.it")


def _normalize_host(entry: str) -> str:
    """Strip scheme/trailing slash so env typos do not break CSRF origins."""
    host = (entry or "").strip()
    if host.startswith("https://"):
        host = host[8:]
    elif host.startswith("http://"):
        host = host[7:]
    return host.rstrip("/")


_allowed = os.environ.get("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = (
    [_normalize_host(h) for h in _allowed.split(",") if _normalize_host(h)] if _allowed else []
)
# Render: aggiunge automaticamente l'hostname del servizio
if _render_hostname and _render_hostname not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_hostname)
# Always allow the public custom domains in production (login POST needs matching CSRF).
if not DEBUG:
    for _prod_host in _PRODUCTION_HOSTS:
        if _prod_host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_prod_host)

# CSRF trusted origins (comma-separated), with Render hostname auto-added.
_csrf_trusted = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_trusted.split(",") if o.strip()] if _csrf_trusted else []


def _add_csrf_origin(host: str) -> None:
    host = _normalize_host(host)
    if not host or host.startswith("."):
        return
    origin = f"https://{host}"
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)


if _render_hostname:
    _add_csrf_origin(_render_hostname)
for _host in ALLOWED_HOSTS:
    _add_csrf_origin(_host)
if not DEBUG:
    for _prod_host in _PRODUCTION_HOSTS:
        _add_csrf_origin(_prod_host)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'axes',
    'tools',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Login brute-force protection (django-axes)
_axes_enabled_raw = os.environ.get("AXES_ENABLED")
AXES_ENABLED = (
    _axes_enabled_raw.strip().lower() not in ("0", "false", "no", "off")
    if _axes_enabled_raw is not None
    else True
)
AXES_FAILURE_LIMIT_DEFAULT = 5
AXES_FAILURE_LIMIT_STAFF = 3
AXES_FAILURE_LIMIT = "tools.auth_throttle.axes_failure_limit"
AXES_COOLOFF_TIME = 0.25  # 15 minutes
AXES_LOCK_OUT_AT_FAILURE = True
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]
AXES_RESET_ON_SUCCESS = True
AXES_RESET_COOL_OFF_ON_FAILURE_DURING_LOCKOUT = False
AXES_COOLOFF_MESSAGE = _(
    "Too many login attempts. Please try again in 15 minutes."
)
AXES_LOCKOUT_TEMPLATE = "registration/account_lockout.html"
AXES_USERNAME_CALLABLE = "tools.auth_throttle.axes_username_callable"
# Behind Render / reverse proxies, prefer X-Forwarded-For when present.
AXES_IPWARE_META_PRECEDENCE_ORDER = (
    "HTTP_X_FORWARDED_FOR",
    "REMOTE_ADDR",
)
if _is_render:
    AXES_IPWARE_PROXY_COUNT = 1
    AXES_IPWARE_PROXY_ORDER = "left-most"

# Password reset / verification email throttles (DB-backed, no Redis)
AUTH_THROTTLE_PASSWORD_RESET_EMAIL_LIMIT = 5
AUTH_THROTTLE_PASSWORD_RESET_IP_LIMIT = 10
AUTH_THROTTLE_PASSWORD_RESET_WINDOW_SECONDS = 3600
AUTH_THROTTLE_RESEND_VERIFY_EMAIL_LIMIT = 5
AUTH_THROTTLE_RESEND_VERIFY_IP_LIMIT = 10
AUTH_THROTTLE_RESEND_VERIFY_WINDOW_SECONDS = 3600

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'tools' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tools.context_processors.canonical_url',
                'tools.context_processors.drose_site',
                'tools.context_processors.user_profile',
                'tools.context_processors.drose_staff_quotes',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 12},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', _('English')),
    ('it', _('Italian')),
]

# Single source of truth for project strings (never use BASE_DIR / "locale" here:
# a stray root catalog overrides these and breaks the site).
LOCALE_PATHS = [BASE_DIR / "tools" / "locale"]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# settings.py

STATIC_URL = '/static/'

# In fase di sviluppo, dovresti avere qualcosa del genere per i tuoi file statici:
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'tools/static'),  # Assicurati che punti alla tua cartella static
]

# In produzione (se usi collectstatic), STATIC_ROOT dovrebbe essere configurato
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media (user uploads: avatars, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Login / Logout
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'

# Email (for password reset and verification)
_email_host_raw = (os.environ.get('EMAIL_HOST') or '').strip()
_email_port_raw = (os.environ.get('EMAIL_PORT') or '587').strip()
_email_tls_raw = (os.environ.get('EMAIL_USE_TLS') or 'true').strip().lower()
_email_user_raw = (os.environ.get('EMAIL_HOST_USER') or '').strip()
_email_pass_raw = (os.environ.get('EMAIL_HOST_PASSWORD') or '').strip()
_sendgrid_key_raw = (os.environ.get('SENDGRID_API_KEY') or '').strip()
if DEBUG and not _email_host_raw and not _sendgrid_key_raw:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    EMAIL_HOST = ''
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = ''
    EMAIL_HOST_PASSWORD = ''
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = _email_host_raw or 'smtp.sendgrid.net'
    try:
        EMAIL_PORT = int(_email_port_raw)
    except Exception:
        EMAIL_PORT = 587
    EMAIL_USE_TLS = _email_tls_raw in ('1', 'true', 'yes', 'on')
    EMAIL_HOST_USER = _email_user_raw or 'apikey'
    EMAIL_HOST_PASSWORD = _email_pass_raw or _sendgrid_key_raw
    EMAIL_TIMEOUT = int((os.environ.get('EMAIL_TIMEOUT') or '20').strip() or '20')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Gadly Support <contact@gadly.it>')
DROSE_QUOTE_EMAIL = (os.environ.get('DROSE_QUOTE_EMAIL') or '').strip()
try:
    DROSE_QUOTE_TRASH_RETENTION_DAYS = max(
        1,
        int((os.environ.get('DROSE_QUOTE_TRASH_RETENTION_DAYS') or '60').strip()),
    )
except ValueError:
    DROSE_QUOTE_TRASH_RETENTION_DAYS = 60

# Require verified email before login for regular users.
# In local dev (DEBUG=True) default is disabled to avoid lockout during testing.
_email_verify_raw = os.environ.get('EMAIL_VERIFICATION_REQUIRED_LOGIN')
if _email_verify_raw is None:
    EMAIL_VERIFICATION_REQUIRED_LOGIN = not DEBUG
else:
    EMAIL_VERIFICATION_REQUIRED_LOGIN = _email_verify_raw.strip().lower() in ('1', 'true', 'yes', 'on')

# Local AI for Interview Simulator (no external APIs).
INTERVIEW_AI_ENABLED = os.environ.get('INTERVIEW_AI_ENABLED', '0').strip().lower() in ('1', 'true', 'yes', 'on')
INTERVIEW_AI_ENDPOINT = os.environ.get('INTERVIEW_AI_ENDPOINT', 'http://127.0.0.1:11434/api/generate').strip()
INTERVIEW_AI_MODEL = os.environ.get('INTERVIEW_AI_MODEL', 'llama3.1:8b').strip()
try:
    INTERVIEW_AI_TIMEOUT_SECONDS = max(2, min(180, int(os.environ.get('INTERVIEW_AI_TIMEOUT_SECONDS', '8'))))
except Exception:
    INTERVIEW_AI_TIMEOUT_SECONDS = 8

# Impostazioni di sicurezza per produzione (quando DEBUG=False)
if not DEBUG:
    # Render/Proxy support: trust forwarded https header.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Share session/CSRF across gadly.it and www.gadly.it
    SESSION_COOKIE_DOMAIN = ".gadly.it"
    CSRF_COOKIE_DOMAIN = ".gadly.it"
