from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('faq/', views.faq, name='faq'),
    path('privacy/', views.privacy, name='privacy'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('word-counter/', views.word_counter, name='word_counter'),
    path('calculator/', views.calculator, name='calculator'),
    path('Percentage/', views.calculator_single, {'panel': 'percent'}, name='calc_percentage'),
    path('VAT/', views.calculator_single, {'panel': 'iva'}, name='calc_vat'),
    path('Net-Salary/', views.calculator_single, {'panel': 'salary'}, name='calc_net_salary'),
    path('Interest/', views.calculator_single, {'panel': 'interest'}, name='calc_interest'),
    path('Currency/', views.calculator_single, {'panel': 'currency'}, name='calc_currency'),
    path('Loan/', views.calculator_single, {'panel': 'loan'}, name='calc_loan'),
    path('Discount/', views.calculator_single, {'panel': 'discount'}, name='calc_discount'),
    path('Margin/', views.calculator_single, {'panel': 'margin'}, name='calc_margin'),
    path('Split-Bill/', views.calculator_single, {'panel': 'split'}, name='calc_split_bill'),
    path('translator/', views.translator, name='translator'),
    path('translate/', views.translate_text, name='translate_text'),
    path('file-analyzer/', views.file_analyzer, name='file_analyzer'),
    path('analyze-file/', views.analyze_file, name='analyze_file'),
    path('image-editor/', views.image_editor, name='image_editor'),
    path('api/image-remove-bg/', views.image_remove_bg_api, name='image_remove_bg_api'),
    path('api/image-upscale/', views.image_upscale_api, name='image_upscale_api'),
    path('data-viz/', views.data_viz, name='data_viz'),
    path('pdf-merger/', views.pdf_merger, name='pdf_merger'),
    path('pdf-split/', views.pdf_split, name='pdf_split'),
    path('qr-generator/', views.qr_generator, name='qr_generator'),
    path('password-gen/', views.password_gen, name='password_gen'),
    path('remove-spaces/', views.remove_spaces, name='remove_spaces'),
    path('username-generator/', views.username_generator, name='username_generator'),
    path('bio-generator/', views.bio_generator, name='bio_generator'),
    path('meta-tag-checker/', views.meta_tag_checker, name='meta_tag_checker'),
    path('sitemap-extractor/', views.sitemap_extractor, name='sitemap_extractor'),
    path('robots-txt-generator/', views.robots_txt_generator, name='robots_txt_generator'),
    path('site-speed-check/', views.site_speed_check, name='site_speed_check'),
    path('api/meta-tag-check/', views.meta_tag_check_api, name='meta_tag_check_api'),
    path('api/sitemap-extract/', views.sitemap_extract_api, name='sitemap_extract_api'),
    path('api/site-speed/', views.site_speed_api, name='site_speed_api'),
    path('hashtag-generator/', views.hashtag_generator, name='hashtag_generator'),
    path('caption-generator/', views.caption_generator, name='caption_generator'),
    path('video-downloader/', views.video_downloader, name='video_downloader'),
    path('api/video-download/', views.video_download_api, name='video_download_api'),
]

