# Generated by Django 6.0.4 on 2026-06-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_userprofile_pending_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroseQuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=32, unique=True)),
                ('response_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('offer_sent', 'Offer sent'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='received', max_length=20)),
                ('language', models.CharField(default='en', max_length=5)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('company_name', models.CharField(blank=True, default='', max_length=160)),
                ('service_type', models.CharField(max_length=32)),
                ('service_label', models.CharField(max_length=120)),
                ('deliverables', models.JSONField(blank=True, default=list)),
                ('deliverables_label', models.TextField(blank=True, default='')),
                ('budget_range', models.CharField(max_length=32)),
                ('budget_label', models.CharField(max_length=64)),
                ('location', models.CharField(blank=True, default='', max_length=160)),
                ('preferred_timeline', models.CharField(blank=True, default='', max_length=120)),
                ('reference_links', models.CharField(blank=True, default='', max_length=500)),
                ('project_details', models.TextField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('offer_scope', models.TextField(blank=True, default='')),
                ('offer_deliverables', models.JSONField(blank=True, default=list)),
                ('price_subtotal', models.CharField(blank=True, default='', max_length=64)),
                ('price_total', models.CharField(blank=True, default='', max_length=64)),
                ('offer_timeline', models.TextField(blank=True, default='')),
                ('offer_notes', models.TextField(blank=True, default='')),
                ('offer_sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
