# Generated by Django 6.0.4 on 2026-07-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_droseworkitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(db_index=True, max_length=40)),
                ('identifier', models.CharField(db_index=True, max_length=190)),
                ('count', models.PositiveIntegerField(default=0)),
                ('window_starts', models.DateTimeField()),
                ('window_ends', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['window_ends'], name='auth_throttle_window_ends')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'identifier'), name='unique_auth_throttle_scope_identifier')],
            },
        ),
    ]
